server:
  port: 8082
sidpik:
  environment: LOCAL
  scrap:
    pointsTableUrl: https://www.iplt20.com/points-table/men/2024
spring:
  application:
    name: sportify-backend-api
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb+srv://rahmansaifi363:HUBol0DU3r7Ru3Nf@cluster0.awywiup.mongodb.net/sportify-backend-api?retryWrites=true&w=majority&appName=Cluster0
