server:
  port: 8083
sidpik:
  environment: PROD
spring:
  application:
    name: sportify-backend-api
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb+srv://vishesh:vishesh12345@cluster0.sbeclcx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0