server:
  port: 8082
sidpik:
  environment: PROD
spring:
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://mongo:yVpOervNTOrbdJOHoejtZvYAYwMLQHBA@viaduct.proxy.rlwy.net:10124/sportify-ipl
